name: deploy

on: # main branch push 시 동작
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  # Java
  JAVA_VERSION: 11
  # DockerHub
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  # AWS & Elastic Bean Stalk
  AWS_REGION: ap-northeast-2
  EB_ENVIRONMENT_NAME: elasticbeanstalk-env
  EB_APPLICATION_NAME: elasticbeanstalk-dev
  EB_DEPLOYMENT_PACKAGE: Dockerrun.aws.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t project_graphql .
          docker tag project_graphql comeevery/project_graphql:latest
          docker push comeevery/project_graphql:latest

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: Version ${{steps.build-number.outputs.BUILD_NUMBER}} deployed via github actions ${{ github.sha }}
          wait_for_deployment: 60